/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;
import model.bean.EncomendaBEAN;
import model.dao.EncomendaDAO;

/**
 *
 * @author rafae
 */
public class EncomendaListar extends javax.swing.JInternalFrame {

    /**
     * Creates new form EncomendaListar
     */
    JDesktopPane index;
    DefaultTableModel table;
    public EncomendaListar(JDesktopPane desktop) {
        super("LISTA DE ENCOMENDAS");
        EncomendaDAO dao = new EncomendaDAO();
        index = desktop;
        initComponents();
        table = (DefaultTableModel) Tabela.getModel();
        for (EncomendaBEAN ecomendas : dao.read()) {
            Object[] dados = {ecomendas.getCodigo(), ecomendas.getProduto(),ecomendas.getDescricao(), ecomendas.getStatus(), ecomendas.getData(), ecomendas.getPrevisao(), ecomendas.getQuantidade(),ecomendas.getValor()};
            table.addRow(dados);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Produto", "Descrição", "Status", "Data", "Previsão", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtualizar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar)
                .addGap(8, 8, 8)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cod = txtBuscar.getText();
        EncomendaDAO dao = new EncomendaDAO();
        table.setNumRows(0);
        for (EncomendaBEAN ecomendas : dao.getCodigo(cod)) {
            Object[] dados = {ecomendas.getCodigo(), ecomendas.getProduto(),ecomendas.getDescricao(), ecomendas.getStatus(), ecomendas.getData(), ecomendas.getPrevisao(), ecomendas.getQuantidade(),ecomendas.getValor()};
            table.addRow(dados);
    }//GEN-LAST:event_btnBuscarActionPerformed
   }
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
         table.setNumRows(0);
        EncomendaDAO dao = new EncomendaDAO();
        for (EncomendaBEAN ecomendas : dao.read()) {
            Object[] dados = {ecomendas.getCodigo(), ecomendas.getProduto(),ecomendas.getDescricao(), ecomendas.getStatus(), ecomendas.getData(), ecomendas.getPrevisao(), ecomendas.getQuantidade(),ecomendas.getValor()};
            table.addRow(dados);
    }//GEN-LAST:event_btnAtualizarActionPerformed
    }
    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
       String codigo = (String) Tabela.getValueAt(Tabela.getSelectedRow(), 0);
        EncomendaEditar ediProduct = new EncomendaEditar(codigo, index);
        ediProduct.setVisible(true); 
    }//GEN-LAST:event_TabelaMouseClicked
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

   
}
